# Generated by Django 5.0.1 on 2024-01-23 15:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название привычки')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='место выполнения привычки')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='время выполнения привычки')),
                ('action', models.CharField(max_length=100, verbose_name='действие привычки')),
                ('good_habit', models.BooleanField(default=True, verbose_name='признак приятной привычки')),
                ('period', models.CharField(choices=[('ежедневно', 'ежедневно'), ('еженедельно', 'еженедельно')], default='ежедневно', max_length=20, verbose_name='периодичность привычки')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='продолжительность выполнения привычки')),
                ('public_habit', models.BooleanField(default=True, verbose_name='признак публичной привычки')),
                ('prize', models.CharField(blank=True, max_length=100, null=True, verbose_name='вознаграждение')),
                ('connected_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='связанная привычка')),
            ],
        ),
    ]
